### PR TITLE
fix(core): allow users to assign custom colors to the links of source nodes

### LINKED ISSUE #1175: [Enhancement]: Allow users to select custom colors for nodes in alluvial
### Contact Details

_No response_

### What happened?

User's should be able to select custom node coloring by node names similar to the custom colors section in the demo site.

### Version

NA

### Data & options used

```js
const alluvialSimpleOptions = {
	title: 'Alluvial',
	alluvial: {
		units: 'GB',
		nodes: [
			{ name: 'A', category: 'Start' },
			{ name: 'B', category: 'Start' },
			{ name: 'C', category: 'Start' },
			{ name: 'X', category: 'Finish' },
			{ name: 'Y', category: 'Finish' },
			{ name: 'Z', category: 'Finish' },
		],
	},
        color: {
		scale: {
			A: 'red',
			B: 'yellow',
			C: 'blue',
		},
	},
};
```

### Relevant log output

_No response_

### Codesandbox example

_No response_

### PR DESCRIPTION
**Pull request by Akshat55**
### Updates
- Allow users to assign custom colors to node links from source
- Create a demo for it

fix #1175 

### Demo screenshot or recording
image

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

File: packages/core/demo/data/alluvial.ts [hunk 1]
```diff
@@ -25,6 +25,18 @@ export const alluvialSimpleOptions = {
...
 };
 
+export const alluvialSimpleCustomColorOptions = {
+	...alluvialSimpleOptions,
+	title: 'Custom colors (alluvial)',
+	color: {
+		scale: {
+			A: 'red',
+			B: 'yellow',
+			C: 'blue',
```
Comment (theiliad) [inline packages/core/demo/data/alluvial.ts:35]: Could we pls just tone down the colors a little bit?

**Review by theiliad — CHANGES_REQUESTED** [review]

File: packages/core/demo/data/alluvial.ts (hunk 1 above)
Comment (theiliad) [reply packages/core/demo/data/alluvial.ts:35]: you could even use the palette https://www.carbondesignsystem.com/data-visualization/color-palettes/

Comment (Akshat55) [reply packages/core/demo/data/alluvial.ts]: image
