### PR TITLE
fix(core): display the correct group when hovering over scatter point

### LINKED ISSUE #1188: [Bug]: Stack Area chart tooltip doesn't display the correct group as selected in the legend
### Contact Details

bikash.pattnayak@gmail.com

### What happened?

Tooltip does not show the correct group. This issue i can reproduce in the storybook demo as well.
https://charts.carbondesignsystem.com/angular/?path=/story/simple-charts-area-stacked--stacked-area-time-series-with-uneven-data

Just select any group from the legend and hover over the chart to see the tooltip. The tooltip group displayed doesn't match the legend selected.
image

### Version

0.50.7. 
This  can reproduced in any older version as well.

### Data & options used

_No response_

### Relevant log output

_No response_

### Codesandbox example

_No response_

### PR DESCRIPTION
**Pull request by Akshat55**
### Updates
- Render the scatter points only if the status of the data group is true.

fix #1188

### Demo screenshot or recording
image

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

File: packages/core/src/components/graphs/scatter-stacked.ts [hunk 1]
```diff
@@ -30,6 +30,9 @@ export class StackedScatter extends Scatter {
 			percentage,
 		});
 
+		// Organize the data based on the active data groups
+		const dGroups = this.model.getDataGroups();
```
Comment (theiliad) [inline packages/core/src/components/graphs/scatter-stacked.ts:34]:
```suggestion
		const dataGroups = this.model.getDataGroups();
```

Comment (theiliad) [reply packages/core/src/components/graphs/scatter-stacked.ts:34]: let's just use full names

**Review by theiliad — CHANGES_REQUESTED** [review]

**Review by theiliad — APPROVED** [review]

**Review by theiliad — APPROVED** [review]
