### PR TITLE
improvement(core): keyboard-navigatable legend items & accessibility fixes

### LINKED ISSUE #762: [AVT1] <Notifications> Multiple elements with the WAI-ARIA role 'group' must not use the same label.
Charts version
"@carbon/charts": "^0.34.5",

Each element with "group" role must have a unique label that describes its purpose.
This issue happens when we have multiple Donut charts on the page. As we have multiple charts, the same aria-lable is repeated for all the donuts and hence the issue.

Soln could be, there should be a way to set the aria_label from the user.
image

image

### LINKED ISSUE #806: AVT3: JAWS does not recognize Invalid, Sent, Seen and Open as checkbox on Monitor page
Charts version
"@carbon/charts": "^0.34.5",

=====ENVIRONMENT=====

Test Tool: JAWS Screen Reader 2019
IBM CI 162 Checkpoint Violation: IBM 1.3.1 Info and Relationships
IBM CI 162 Checkpoint Violation: IBM 3.3.2 Labels and Instructions
IBM Guidance: https://www.ibm.com/able/guidelines/ci162/info_and_relationships.html
IBM Guidance: https://www.ibm.com/able/guidelines/ci162/labels_or_instructions.html

=====DEFECT DESCRIPTION=====
JAWS does not recognize Invalid, Sent, Seen and Open as checkbox, they are read as Invalid graphic, Sent graphic, Seen graphic and Open graphic.

image

### PR DESCRIPTION
**Pull request by theiliad**
Closes #762 
Closes #806

### CODE REVIEW

File: packages/core/src/components/essentials/legend.ts [hunk 1]
```diff
@@ -388,5 +394,14 @@ export class Legend extends Component {
 					}
 				);
 			});
+
+		svg.selectAll("g.legend-item rect.checkbox").on("keyup", function (d) {
+			const { keyCode } = event;
+			if (keyCode === 32 || keyCode === 13) {
```
Comment (zvonimirfras) [inline packages/core/src/components/essentials/legend.ts:400]: `keyCode` is deprecated 😉

**Review by cal-smith — DISMISSED** [review]

**Review by zvonimirfras — APPROVED** [review]

**Review by sophiiae — APPROVED** [review]
