### PR TITLE
fix(core): prevent chart from breaking if thresholds array is empty 

### LINKED ISSUE #1264: [Bug]: Empty threshold list crashes chart due to undefined values
### Contact Details

mail@lindener.it

### What happened?

When the thresholds array is empty, calculating the highest threshold fails at this line:
https://github.com/carbon-design-system/carbon-charts/blob/a55be0fcec6020b609ab18b2224562aaa9775321/packages/core/src/services/scales-cartesian.ts#L763

A simple fix would be to enhance the check for threshold === null to also include length of the array.
https://github.com/carbon-design-system/carbon-charts/blob/a55be0fcec6020b609ab18b2224562aaa9775321/packages/core/src/services/scales-cartesian.ts#L757

If you are interested I can provide the respective pull request.

### Version

latest

### Data & options used

```js
Check the code sandbox
```

### Relevant log output

```
TypeError
highestThreshold is undefined
$csb$eval/CartesianScales.prototype.getHighestDomainThreshold@https://v8zkk.csb.app/node_modules/
carbon/charts/services/scales-cartesian.js:509:66
$csb$eval/Scatter.prototype.isDatapointThresholdAnomaly@https://v8zkk.csb.app/node_modules/
carbon/charts/components/graphs/scatter.js:149:105
$csb$eval/Scatter.prototype.styleCircles/<@https://v8zkk.csb.app/node_modules/
carbon/charts/components/graphs/scatter.js:191:20
classedFunction/<
https://v8zkk.csb.app/node_modules/d3-selection/src/selection/classed.js:54:12
$csb__default
https://v8zkk.csb.app/node_modules/d3-selection/src/selection/each.js:8:37
$csb__default
https://v8zkk.csb.app/node_modules/d3-selection/src/selection/classed.js:64:15
$csb$eval/Scatter.prototype.styleCircles@https://v8zkk.csb.app/node_modules/
carbon/charts/components/graphs/scatter.js:190:8
$csb$eval/Scatter.prototype.render@https://v8zkk.csb.app/node_modules/
carbon/charts/components/graphs/scatter.js:138:10
$csb$eval/LayoutComponent.prototype.render/</<@https://v8zkk.csb.app/node_modules/
carbon/charts/components/layout/layout.js:137:25
$csb$eval/LayoutComponent.prototype.render/<@https://v8zkk.csb.app/node_modules/
carbon/charts/components/layout/layout.js:134:20
```

### Codesandbox example

https://codesandbox.io/s/priceless-sunset-v8zkk?file=/src/index.js

### PR DESCRIPTION
**Pull request by Akshat55**
### Updates
- Checks to see if thresholds is an array and an additional check to see if it is empty
  - Prevents chart from crashing
- Formats (other) files

fix #1264 

### Demo screenshot or recording
N/A - any cartesian chart with thresholds set to empty array:
```json
options: {
axes: {
  left: { thresholds: [] }
}
}
```

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

File: packages/core/src/services/scales-cartesian.ts [hunk 1]
```diff
@@ -754,7 +754,11 @@ export class CartesianScales extends Service {
...
 		const { thresholds } = axesOptions[domainAxisPosition];
 
-		if (!thresholds) {
+		// Check if thresholds exist & is not empty
+		if (
+			!Array.isArray(thresholds) ||
+			(Array.isArray(thresholds) && !thresholds.length)
+		) {
 			return null;
 		}
```
Comment (Akshat55) [inline packages/core/src/services/scales-cartesian.ts:763]: This check is done in only 2 places - `getHighestDomainThreshold()` and `getHighestRangeThreshold()` functions

**Review by theiliad — APPROVED** [review]
