### PR TITLE
fix(core): add missing properties to AxisOptions interface

### LINKED ISSUE #1413: [Bug]: Multi-axis properties missing from types
### Contact Details

_No response_

### What happened?

The properties `main` and `correspondingDatasets` used for multi-axis setups (as described in https://github.com/carbon-design-system/carbon-charts/blob/80f53aafe3f87012caedeb77605559e8ee402bdf/packages/core/stories/tutorials/dual-axes.ts) are missing from the documentation at https://charts.carbondesignsystem.com/documentation/interfaces/_interfaces_axis_scales_.axisoptions.html and from the TypeScript definitions.

### Version

`@carbon/charts-svelte@1.3.2`

### Data & options used

```js
        const options: ScatterChartOptions = {
		axes: {
			bottom: {
				mapsTo: 'time',
				scaleType: 'time' as ScaleTypes.TIME
			},
			left: {
				mapsTo: 'power',
				main: true
                                // TypeScript Error: Object literal may only specify known properties, and 'main' does not exist in type 'AxisOptions'.
			},
			right: {
				mapsTo: 'temperature',
				correspondingDatasets: ['Temperature']
                                // TypeScript error: Object literal may only specify known properties, and 'correspondingDatasets' does not exist in type 'AxisOptions'.
			}
		}
	};
```

### Relevant log output

_No response_

### Codesandbox example

_No response_

### PR DESCRIPTION
**Pull request by metonym**
Fixes #1413

The `AxisOptions` interface is missing `main` and `correspondingDatasets` properties to support dual-axes charts.

### Updates
- add missing properties to AxisOptions interface

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

File: packages/core/src/interfaces/axis-scales.ts [hunk 1]
```diff
@@ -124,6 +124,15 @@ export interface AxisOptions extends BasedAxisOptions {
...
 	percentage?: boolean;
+	/**
+	 * should be set to `true` for the
+	 * left axis to be the primary axis
+	 */
+	main?: boolean;
+	/**
+	 * used to map data on the secondary axis
+	 */
+	correspondingDatasets?: Array<string>;
```
Comment (theiliad) [inline packages/core/src/interfaces/axis-scales.ts:135]: Hi @metonym, we should probably find a way to have this only affect combo charts, since they mostly wouldn't apply to others

**Review by theiliad — CHANGES_REQUESTED** [review]

File: packages/core/src/interfaces/axis-scales.ts (hunk 1 above)
Comment (metonym) [reply packages/core/src/interfaces/axis-scales.ts]: https://github.com/carbon-design-system/carbon-charts/commit/8b492e0329829cc9619faea88605def7e463b933

- created a `ComboChartAxisOptions` interface
- updated `ComboChartOption.axes` to use `ComboChartAxisOptions`

**Review by theiliad — APPROVED** [review]
amazing! thanks Eric for the quick update 🙂

File: packages/core/src/interfaces/axis-scales.ts (hunk 1 above)
Comment (cloudlena) [reply packages/core/src/interfaces/axis-scales.ts:138]: @theiliad, I don't get it. Why shouldn't I use these properties in `ScatterChartOptions` as described in my example in https://github.com/carbon-design-system/carbon-charts/issues/1413? For me, this issue doesn't seem to be fixes as I was trying to use them in a `ScatterChartOptions`.
