### PR TITLE
fix(core): keep radar chart alignment after fullscreen exit

### LINKED ISSUE #1247: [Bug]: Radar chart is no longer aligned after exiting full screen
### Contact Details

_No response_

### What happened?

Radar alignment is incorrect after exiting full screen. This behavior is noticeable when initial alignment is set to "center" or "right". 

image

### Version

Latest

### Data & options used

```js
...
  "radar": {
    "axes": {
      "angle": "feature",
      "value": "score"
    },
    "alignment": "center" || "right"
  },
...
```

### Relevant log output

_No response_

### Codesandbox example

_No response_

### PR DESCRIPTION
**Pull request by Akshat55**
### Updates
- Align the chart after the transitions are complete, previously alignment was triggered async which caused it to be misaligned after fullscreen exit

fix #1247

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

File: packages/core/src/components/graphs/radar.ts [hunk 1]
```diff
@@ -444,6 +444,22 @@ export class Radar extends Component {
...
+								'alignment'
+							);
+
+							const alignmentXOffset = this.getAlignmentXOffset(
+								alignment,
+								svg,
+								this.getParent()
+							);
+							svg.attr('x', alignmentXOffset);
+						})
```
Comment (theiliad) [inline packages/core/src/components/graphs/radar.ts:462]: this is running after .update(), what about .enter()?

**Review by theiliad — CHANGES_REQUESTED** [review]

File: packages/core/src/components/graphs/radar.ts (hunk 1 above)
Comment (Akshat55) [reply packages/core/src/components/graphs/radar.ts:462]: .enter() will be called only once - when the radar chart is being created. Hence, it makes more sense to add it to update since the element exists and the position can be realigned when any changes are made.

I cannot chain the promise to the .call function. If I chain it inside the call function, then the alignment will be incorrect on fullscreen exit. This is the same case if I were to add the above code to **both** enter and update.

**Review by theiliad — APPROVED** [review]
