### PR TITLE
fix(core): enable heatmap value domain to support small values

### LINKED ISSUE #1321: [Bug]: Heatmap domain does not support small values (Including legend)
### What happened?

While implementing a heatmap chart that has very small values (0 to 1) I've noticed that the legend/color scaling seems  to be locked to 1-10 at a minimum. From what I can tell there is no way to override this behavior via the options object and it results in a heatmap where a majority of the cells are the lowest legend color:

image
 
I am hoping I'm missing a configuration or workaround as this unfortunately makes the heatmap un-usable for datasets with small values.

### Version

"@carbon/charts-svelte": "0.54.12"

### Data & options used

```js
const data = [
	  {
	    letter: "A",
	    month: "January",
	    value: 41
	  },
	  {
	    letter: "B",
	    month: "January",
	    value: 7
	  },
	  {
	    letter: "C",
	    month: "January",
	    value: 66
	  },
	  {
	    letter: "D",
	    month: "January",
	    value: 85
	  },
	 // continued in code sandbox
	].map(entry => ({
	  ...entry,
	  value: entry.value / 100
	}));

const options = {
	"title": "Heatmap (Quantize legend)",
	"axes": {
		"bottom": {
			"title": "Letters",
			"mapsTo": "letter",
			"scaleType": "labels"
		},
		"left": {
			"title": "Months",
			"mapsTo": "month",
			"scaleType": "labels"
		}
	},
	"heatmap": {
		"colorLegend": {
			"title": "Legend title",
			"type": "quantize"
		}
	},
	"experimental": true,
	"height": "400px"
}
```

### Relevant log output

_No response_

### Codesandbox example

https://codesandbox.io/s/epic-franklin-cv1nz0?file=/App.svelte

### PR DESCRIPTION
**Pull request by Akshat55**
### Updates
- Heatmap domain now supports small values (No user change required)

### Demo screenshot or recording
image

fix #1321

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

File: packages/core/src/model/heatmap.ts [hunk 1]
```diff
@@ -48,29 +48,18 @@ export class HeatmapModel extends ChartModelCartesian {
...
-			domain.push(value);
-		});
+		const limits = extent(this.getDisplayData(), (d: any) => d.value);
+		const domain = scaleLinear()
+			.domain(limits as [number, number])
+			.nice()
+			.domain();
+
+		// Ensuring limits start at 0 to make scale look more `nicer`
+		if (domain[0] > 0) {
```
Comment (theiliad) [inline packages/core/src/model/heatmap.ts:58]: is this correct? what if limits or domain include negative values?

**Review by theiliad — CHANGES_REQUESTED** [review]
@Akshat55 do we have a demo to show this functionality?

**Comment by Akshat55** [comment]
Added demo where we are using small numbers (0 - 10) and divergent color scheme

image

File: packages/core/src/model/heatmap.ts (hunk 1 above)
Comment (Akshat55) [reply packages/core/src/model/heatmap.ts:58]: Yes, this is the same as what I was doing previously:
```js
if (index === 0 && value >= 0) {
	value = 0;
}
```

If the number is positive, it'll set the minimum in the domain to 0 - Cartesian service does something similar but for axis

**Review by theiliad — APPROVED** [review]
